version: '3.5'
services:
  ms:
    build: .
    image: billing-batch:latest
    container_name: billing-batch
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      ENV: local
      RABBIT_HOST: biling-rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
    networks:
      - fiap-billing-network

networks:
  fiap-billing-network:
    external: true
    name: fiap-billing-network
